### PR TITLE
Add exp python

### PR DESCRIPTION
**Pull request by aj-ptw**
# 1.4.3

### New examples
* Add example of node to python

### CODE REVIEW

**Comment by teonbrooks** [comment]
🍻

**Comment by aj-ptw** [comment]
🍗🍗💯

**Comment by teonbrooks** [comment]
hey, so I manage to get everything installed and I connected to the simulated board, but I am not clear on how the interaction with the board works. I instantiated an `Interface` obj. do I send the command with the `send` method? are these the same function names from the js module?

**Comment by aj-ptw** [comment]
@teonbrooks you can see an [example of sending from python to node here](https://github.com/OpenBCI/OpenBCI_NodeJS/blob/master/examples/python/handoff.py#L106-L110)

**Pull request merged**
