### PR TITLE
Lab Streaming Layer example

### PR DESCRIPTION
**Pull request by gabrielibagon**
I figured it would be good to add an example of working code for streaming through LSL using the NodeJS SDK . This uses a modified version of the NodeJS -> Python technique shown in the other example file. The code is ready to stream as-is, which should make this directory useful for people who would like to just start streaming on LSL right away.

Equivalent code for the ganglion is mostly written using the same technique (though I'm running into the roadblock in [this Ganglion issue](https://github.com/OpenBCI/OpenBCI_NodeJS_Ganglion/issues/23)!) If this looks good to you, I'll post a pull request there once it's done.

### CODE REVIEW

**Comment by aj-ptw** [comment]
@gabrielibagon 

1. This is awesome!
2. Should we remove https://github.com/OpenBCI/OpenBCI_NodeJS#-interfacing-with-other-tools and link to the example you wrote?
3. Ganglion issue https://github.com/OpenBCI/OpenBCI_NodeJS_Ganglion/issues/23 has been closed and you may continue your development!
4. I see no issue with merging this, I just want to add more links to this in the main [readme](https://github.com/OpenBCI/OpenBCI_NodeJS/blob/master/README.md)

**Comment by aj-ptw** [comment]
Yessss good work Gabe!!!!

**Comment by gabrielibagon** [comment]
Woo, thanks! Documentation should be finished. I'll be using this a ton over the next week or two, so I'll be keeping an eye out for any issues that pop up.

**Comment by aj-ptw** [comment]
@gabrielibagon great job! merged!

**Pull request merged**
